### ISSUE TITLE
add debug mode to minishell compilation 

### ISSUE THREAD

**Issue by alx-sch** [multitudes/beash-minishell#25]
#ifdef NDEBUG
#define debug(M, ...)
#else
#define debug(M, ...) fprintf(stderr, "DEBUG %s:%d: " M "\n",\
        __FILE__, __LINE__, ##__VA_ARGS__)
#endif

**Comment by multitudes** [comment]
@alx-sch  
Implemented! 

best way to use it is to redirect the error output to a log file when starting the program...

```bash
./minishell 2> error_log.txt
```

now adding this in main for example:
```
int	main(int argc, char **argv, char **envp)
{
	debug("argc: %d", argc);
	return (loop(argc, argv, envp));
}
```

will print this to the file 
```txt
DEBUG src/main.c:24: argc: 1
```
and leave the terminal free of debug messages

when the 

is uncommented no debug messages will be printed

can use also like launching the program as  
```
./minishell 2>> error_log.txt 
```
to print stderror to a file and have 
all debug messages together...
